name: Deploy to Huawei Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          # 1. Masuk folder project
          cd /root/riziq

          # 2. Tarik kode terbaru
          git pull origin main

          # 3. MATIKAN PROSES LAMA (Surgical Kill)
          # Tambahkan 5005 karena gateway sekarang disana
          fuser -k 5000/tcp || true
          fuser -k 5001/tcp || true
          fuser -k 5002/tcp || true
          fuser -k 5005/tcp || true
          
          # Tunggu sebentar
          sleep 3

          # 4. Install library
          pip3 install -r requirements.txt || true

          # 5. Nyalakan Service
          # Gateway tidak perlu diset port di command line karena sudah di dalam kodenya (5005)
          nohup python3 server1.py > server1.log 2>&1 &
          nohup python3 server2.py > server2.log 2>&1 &
          nohup python3 gateway.py > gateway.log 2>&1 &
          
          # 6. Cek status
          sleep 2
          ps aux | grep python3
